name: disdrodb-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.1.3
  - h5py=3.7.0
  - netCDF4=1.6.1
  - pyarrow=9.0.0
  - PyYAML=6.0
  - setuptools=65.2.0
  - xarray=2022.6.0
  - sphinx=5.1.1
  - sphinx_rtd_theme=1.0.0
  - jupyter=1.0.0
  - nbsphinx=0.8.9
  - dask[distributed]=2022.9.1
  - pre-commit=2.20.0
  - pytest=7.2.0
  - pydantic=1.10.4
