rainfall_rate_32bit: 'float32'
rainfall_accumulated_32bit: 'float32'
weather_code_synop_4680: 'float32' # 'uint32'
weather_code_synop_4677: 'float32' # 'uint32'
weather_code_metar_4678: 'str'
weather_code_nws: 'str'
reflectivity_32bit: 'float32'
mor_visibility: 'float32'  # 'uint16'
sample_interval: 'float32' # 'uint16'
laser_amplitude: 'float32' #'uint32'
number_particles: 'float32' # 'uint32'
sensor_temperature: 'float32' # 'int8'
sensor_serial_number: 'str'
firmware_iop: 'str'
firmware_dsp: 'str'
sensor_heating_current: 'float32'
sensor_battery_voltage: 'float32'
sensor_status: 'float32' # 'uint8'
start_time: 'str'
sensor_time: 'str'
sensor_date: 'str'
station_name: 'str'
station_number: 'str'
rainfall_amount_absolute_32bit: 'float32'
error_code: 'float32' # 'uint8'
sensor_temperature_pcb: 'float32' # 'int8'
sensor_temperature_receiver: 'float32' # 'int8'
sensor_temperature_trasmitter: 'float32' # 'int8'
rainfall_rate_16_bit_30: 'float32'
rainfall_rate_16_bit_1200: 'float32'
rainfall_accumulated_16bit: 'float32'
reflectivity_16bit: 'float32'
rain_kinetic_energy: 'float32'
snowfall_rate: 'float32'
number_particles_all: 'float32' # 'float32' 'uint32'
list_particles: 'str'
raw_drop_concentration: 'str'
raw_drop_average_velocity: 'str'
raw_drop_number: 'str'
