rainfall_rate_32bit: 'Rainfall rate 32 bit'
rainfall_accumulated_32bit: 'Rainfall accumulated 32 bit'
weather_code_synop_4680: 'Weather code SYNOP 4680'
weather_code_synop_4677: 'Weather code SYNOP 4677'
weather_code_metar_4678: 'Weather code METAR 4678'
weather_code_nws: 'Weather code NWS'
reflectivity_32bit: 'Reflectivity 32 bit'
mor_visibility: 'MOR visibility'
sample_interval: 'Sample interval'
laser_amplitude: 'Laser amplitude'
number_particles: 'Number of detected particles'
sensor_temperature: 'Temperature of the sensor'
sensor_serial_number: 'Serial number of the sensor'
firmware_iop: 'Version IOP firmware'
firmware_dsp: 'Version DSP firmware'
sensor_heating_current: 'Sensor heating current'
sensor_battery_voltage: 'Sensor battery voltage'
sensor_status: 'Sensor status'
start_time: 'Start time'
sensor_time: 'Sensor time'
sensor_date: 'Sensor date'
station_name: 'Station name'
station_number: 'Station number'
rainfall_amount_absolute_32bit: 'Rainfall amount absolute 32 bit'
error_code: 'Error code'
sensor_temperature_pcb: 'Sensor PCB temperature'
sensor_temperature_receiver: 'Sensor receiver temperature'
sensor_temperature_trasmitter: 'Sensor trasmitter temperature'
rainfall_rate_16_bit_30: 'Rainfall rate max 30 mm/h 16 bit'
rainfall_rate_16_bit_1200: 'Rainfall rate max 1200 mm/h 16 bit'
rainfall_accumulated_16bit: 'Rainfall accumulated 16 bit'
reflectivity_16bit: 'Radar reflectivity 16 bit'
rain_kinetic_energy: 'Rain kinetic energy'
snowfall_rate: 'Snowfall rate'
number_particles_all: 'Number of all measured particles'
list_particles: 'List particles detected'
raw_drop_concentration: 'Raw drop concentration'
raw_drop_average_velocity: 'Raw drop average velocity'
raw_drop_number: 'Raw drop number'
