rainfall_rate_32bit: 'mm/h'
rainfall_accumulated_32bit: 'mm'
weather_code_synop_4680: ''
weather_code_synop_4677: ''
weather_code_metar_4678: ''
weather_code_nws: ''
reflectivity_32bit: 'dBz'
mor_visibility: 'm'
sample_interval: 's'
laser_amplitude: ''
number_particles: ''
sensor_temperature: '째C'
sensor_serial_number: ''
firmware_iop: ''
firmware_dsp: ''
sensor_heating_current: 'A'
sensor_battery_voltage: 'V'
sensor_status: ''
start_time: ''
sensor_time: ''
sensor_date: ''
station_name: ''
station_number: ''
rainfall_amount_absolute_32bit: 'mm'
error_code: ''
sensor_temperature_pcb: '째C'
sensor_temperature_receiver: '째C'
sensor_temperature_trasmitter: '째C'
rainfall_rate_16_bit_30: 'mm/h'
rainfall_rate_16_bit_1200: 'mm/h'
rainfall_accumulated_16bit: 'mm'
reflectivity_16bit: 'dBz'
rain_kinetic_energy: 'J/(m**2*h)'
snowfall_rate: 'mm/h'
number_particles_all: ''
list_particles: ''
raw_drop_concentration: 'log10 1/(m3*mm)'
raw_drop_average_velocity: 'm/s'
raw_drop_number: ''

