date:
  n_digits: 6
  n_characters: 8
  n_decimals: 6
  n_naturals: 0
  data_range:
  - 01.01.1990
  - 31.12.2100
  nan_flags: null
  nan_flags: null
time:
  n_digits: 6
  n_characters: 8 
  n_decimals: 6
  n_naturals: 0
  data_range:
  - 00:00:00
  - 23:59:59
  nan_flags: null
status:
  n_digits: 
  n_characters: 
  n_decimals: 
  n_naturals: 
  data_range:
  - 
  - 
  nan_flags: null
interval:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n1:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n2:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n3:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n4:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n5:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n6:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n7:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n8:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n9:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n10:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n11:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n12:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n13:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n14:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n15:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n16:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n17:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n18:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n19:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
n20:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 
  data_range:
  - 0
  - 99
  nan_flags: null
RI:
  n_digits: 7
  n_characters: 8
  n_decimals: 3
  n_naturals: 4
  data_range:
  - 0.0001
  - 999.9999
  nan_flags: null
RA:
  n_digits: 6
  n_characters: 7
  n_decimals: 2
  n_naturals: 4
  data_range:
  - 0.0001
  - 99.9999
  nan_flags: null
RAT:
  n_digits: 6
  n_characters: 7
  n_decimals: 2
  n_naturals: 4
  data_range:
  - 0.0001
  - 99.9999
  nan_flags: null