date: 'object'
time: 'object'
status: 'uint8'
interval: 'uint8'
n1: 'uint8'
n2: 'uint8'
n3: 'uint8'
n4: 'uint8'
n5: 'uint8'
n6: 'uint8'
n7: 'uint8'
n8: 'uint8'
n9: 'uint8'
n10: 'uint8'
n11: 'uint8'
n12: 'uint8'
n13: 'uint8'
n14: 'uint8'
n15: 'uint8'
n16: 'uint8'
n17: 'uint8'
n18: 'uint8'
n19: 'uint8'
n20: 'uint8'
RI: 'float32' # Rain intensity (mm/h)
RA: 'float32' # Rain amount (mm)
RAT: 'float32' # Total rain amount since start of measurement (mm)

# Not present but into the documentation

# Wg: 'float32' # Liquid water content (g/m3)
# float16: 'float32' # Radar reflectivity factor (dB)
# EK: 'object' # Kinetic energy (J/m2)
# EF: 'float32' # Energy flux (j/(m2.h))
# N0: 'float32' # Number concentration (1/(m3.mm))
# Slope: 'object' # Slope (1/mm)
# NDi: 'object' # Number density of drops of the diameter corresponding to a site class i per unit volume (1/(m3.mm))
# Dmax: 'float16' # Largest drop registered during interval t (mm)
# Lamda: 'float16'