date: 
  dtype: object
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
time: 
  dtype: object
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
status: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
interval: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n1: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n2: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n3: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n4: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n5: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n6: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n7: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n8: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n9: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n10: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n11: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n12: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n13: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n14: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n15: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n16: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n17: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n18: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n19: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
n20: 
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
RI: 
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
RA: 
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
RAT: 
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000