date: 'Date of the sensor'
time: 'Time of the sensor'
status: 'Sensor status'
interval: 'Interval time between measurement'
n1: 'Raw data'
n2: 'Raw data'
n3: 'Raw data'
n4: 'Raw data'
n5: 'Raw data'
n6: 'Raw data'
n7: 'Raw data'
n8: 'Raw data'
n9: 'Raw data'
n10: 'Raw data'
n11: 'Raw data'
n12: 'Raw data'
n13: 'Raw data'
n14: 'Raw data'
n15: 'Raw data'
n16: 'Raw data'
n17: 'Raw data'
n18: 'Raw data'
n19: 'Raw data'
n20: 'Raw data'
RI: 'Rain intensity (mm/h)'
RA: 'Rain amount (mm)'
RAT: 'Total rain amount since start of measurement (mm)'