rainfall_rate_32bit: 'mm/h'
rainfall_accumulated_32bit: 'mm'
weather_code_synop_4680: ''
weather_code_synop_4677: ''
weather_code_metar_4678: ''
weather_code_nws: ''
reflectivity_32bit: 'dBz'
mor_visibility: 'm'
sample_interval: 's'
laser_amplitude: ''
number_particles: ''
sensor_temperature: '°C'
sensor_serial_number: ''
firmware_iop: ''
firmware_dsp: ''
sensor_heating_current: 'A'
sensor_battery_voltage: 'V'
sensor_status: ''
start_time: ''
sensor_time: ''
sensor_date: ''
station_name: ''
station_number: ''
rainfall_amount_absolute_32bit: 'mm'
error_code: ''
rainfall_rate_16bit: 'mm/h'
rainfall_rate_12bit: 'mm/h'
rainfall_accumulated_16bit: 'mm'
reflectivity_16bit: 'dBZ'
raw_drop_concentration: '1/(m3*mm)'
raw_drop_average_velocity: 'm/s'
raw_drop_number: ''
