rainfall_rate_32bit:
  description: Rainfall rate
  long_name: Rainfall rate 32 bit
  units: mm/h
rainfall_accumulated_32bit:
  description: Accumulated rain amount over the measurement interval
  long_name: Rainfall accumulated 32 bit
  units: mm
weather_code_synop_4680:
  description: SYNOP weather code according to table 4680 of Parsivel documentation
  long_name: Weather code SYNOP 4680
  units: ""
weather_code_synop_4677:
  description: SYNOP weather code according to table 4677 of Parsivel documentation
  long_name: Weather code SYNOP 4677
  units: ""
weather_code_metar_4678:
  description: METAR/SPECI weather code according to table 4678 of Parsivel documentation
  long_name: Weather code METAR 4678
  units: ""
weather_code_nws:
  description: NWS weather code according to Parsivel documentation
  long_name: Weather code NWS
  units: ""
reflectivity_32bit:
  description: Radar reflectivity
  long_name: Reflectivity 32 bit
  units: dBz
mor_visibility:
  description: Meteorological Optical Range in precipitation
  long_name: MOR visibility
  units: m
sample_interval:
  description: Sample interval
  long_name: Sample interval
  units: s
laser_amplitude:
  description:
    Signal amplitude of the laser strip. A way to monitor if windows are
    dirty or not.
  long_name: Laser amplitude
  units: ""
number_particles:
  description: Number of particles detected and validated
  long_name: Number of detected particles
  units: ""
sensor_temperature:
  description: Temperature in sensor housing
  long_name: Temperature of the sensor
  units: "C"
sensor_serial_number:
  description: Sensor serial number
  long_name: Serial number of the sensor
  units: ""
firmware_iop:
  description: Version IOP firmware
  long_name: Version IOP firmware
  units: ""
firmware_dsp:
  description: Version DSP firmware
  long_name: Version DSP firmware
  units: ""
sensor_heating_current:
  description:
    "Sensor head heating current. Optimum heating output of the sensor
    head heating system can be guaranteed with a power supply voltage > 20 V "
  long_name: Sensor heating current
  units: A
sensor_battery_voltage:
  description: Power supply voltage
  long_name: Sensor battery voltage
  units: V
sensor_status:
  description: Sensor status
  long_name: Sensor status
  units: ""
start_time:
  description: Meausurement start time
  long_name: Start time
  units: ""
sensor_time:
  description: Time of the sensor
  long_name: Sensor time
  units: ""
sensor_date:
  description: Date of the sensor
  long_name: Sensor date
  units: ""
station_name:
  description: Name of the station
  long_name: Station name
  units: ""
station_number:
  description: Number of the station
  long_name: Station number
  units: ""
rainfall_amount_absolute_32bit:
  description: Accumulated rain amount over the measurement interval
  long_name: Rainfall amount absolute 32 bit
  units: mm
error_code:
  description: Error code
  long_name: Error code
  units: ""
rainfall_rate_16bit:
  description: Rainfall rate
  long_name: Rainfall rate 16 bit
  units: mm/h
rainfall_rate_12bit:
  description: Rainfall rate
  long_name: Rainfall rate 12 bit
  units: mm/h
rainfall_accumulated_16bit:
  description: Accumulated rain amount over the measurement interval
  long_name: Rainfall accumulated 16 bit
  units: mm
reflectivity_16bit:
  description: Radar reflectivity
  long_name: Reflectivity 16 bit
  units: dBZ
raw_drop_concentration:
  description: Particle number concentrations per diameter class
  long_name: Raw drop concentration
  units: 1/(m3*mm)
raw_drop_average_velocity:
  description: Average particle velocities for each diameter class
  long_name: Raw drop average velocity
  units: m/s
raw_drop_number:
  description: Drop counts per diameter and velocity class
  long_name: Raw drop number
  units: ""
